// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmPZknRcO_v9gUwIMBa6BRd-8sbpcB_Hw',
    appId: '1:898110178563:web:8fde7c7a273572dd441536',
    messagingSenderId: '898110178563',
    projectId: 'my-todo-list-77874',
    authDomain: 'my-todo-list-77874.firebaseapp.com',
    storageBucket: 'my-todo-list-77874.appspot.com',
    measurementId: 'G-E2FN52CR20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_MwWH_ArS_yaZOYqkLkE0D0XluYWsYfA',
    appId: '1:898110178563:android:9930b7a240a149a5441536',
    messagingSenderId: '898110178563',
    projectId: 'my-todo-list-77874',
    storageBucket: 'my-todo-list-77874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPRZ-kJQz8RJlrsCso71DykyTAO0Ap0HE',
    appId: '1:898110178563:ios:08939ae8b4d39eb1441536',
    messagingSenderId: '898110178563',
    projectId: 'my-todo-list-77874',
    storageBucket: 'my-todo-list-77874.appspot.com',
    androidClientId: '898110178563-885vmejdfk9i5salpkpajp7j7gv2s99t.apps.googleusercontent.com',
    iosClientId: '898110178563-0ivelc8egm6hgt9ltvrcuekhussjmmho.apps.googleusercontent.com',
    iosBundleId: 'br.com.rcsbinfo.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPRZ-kJQz8RJlrsCso71DykyTAO0Ap0HE',
    appId: '1:898110178563:ios:08939ae8b4d39eb1441536',
    messagingSenderId: '898110178563',
    projectId: 'my-todo-list-77874',
    storageBucket: 'my-todo-list-77874.appspot.com',
    androidClientId: '898110178563-885vmejdfk9i5salpkpajp7j7gv2s99t.apps.googleusercontent.com',
    iosClientId: '898110178563-0ivelc8egm6hgt9ltvrcuekhussjmmho.apps.googleusercontent.com',
    iosBundleId: 'br.com.rcsbinfo.todolist',
  );
}
